# Generated by Django 3.1.3 on 2020-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animales_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='especie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='animales',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
