# Generated by Django 3.1.3 on 2020-11-23 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_auto_20201123_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='numero',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
