# Generated by Django 3.1.3 on 2020-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_auto_20201123_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
