# Generated by Django 3.1.3 on 2020-11-23 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_auto_20201123_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='animales',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
