# Generated by Django 3.1.3 on 2020-11-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_animales_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animales',
            old_name='user_id',
            new_name='user',
        ),
    ]
