# Generated by Django 3.1.3 on 2020-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0008_auto_20201123_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animales',
            old_name='user',
            new_name='user_id',
        ),
    ]
